// api/config.ts
export const API_CONFIG = {
  baseURL: "http://localhost:8000/api",
  timeout: 60000,
  endpoints: {
    auth: {
      login: "/web/login",
      register: "/web/register",
      logout: "/web/logout",
      user: "/web/user",
      verifyOtp: "/web/verify-otp",
      checkEmail: "/web/check-email",
      resetPassword: "/web/reset-password",
    },
    residents: {
      getAll: "/web/residents",
      getById: (id: number) => `/web/residents/${id}`,
      create: "/web/residents",
      update: (id: number) => `/web/residents/${id}`,
      delete: (id: number) => `/web/residents/${id}`,
      getByEncoder: (userId: number) => `/web/residents/encoder/${userId}`,
    },
    households: {
      getAll: "/web/households",
      getById: (id: number) => `/web/households/${id}`,
      create: "/web/households",
      update: (id: number) => `/web/households/${id}`,
      delete: (id: number) => `/web/households/${id}`,
      info: "/web/households-info",
      infoById: (id: number) => `/web/households-info/${id}`,
      infoByEncoder: (userId: number) =>
        `/web/households-info/encoder/${userId}`,
    },
    census: {
      create: "/web/census/record",
      getAll: "/web/census/records",
      getById: (id: number) => `/web/census/records/${id}`,
    },
    certifications: {
      getAll: "/web/certifications",
      getById: (id: number) => `/web/certifications/${id}`,
      create: "/web/certifications",
      update: (id: number) => `/web/certifications/${id}`,
      delete: (id: number) => `/web/certifications/${id}`,
      types: "/web/certifications/types",
      typesAll: "/web/certifications/types/all",
      storeType: "/web/certifications/types",
      updateType: (id: number) => `/web/certifications/types/${id}`,
      deleteType: (id: number) => `/web/certifications/types/${id}`,
      approve: (id: number) => `/web/certifications/${id}/approve`,
      reject: (id: number) => `/web/certifications/${id}/reject`,
      generateDocument: (id: number) =>
        `/web/certifications/${id}/generate-document`,
      release: (id: number) => `/web/certifications/${id}/release`,
      receive: (id: number) => `/web/certifications/${id}/receive`,
      download: (id: number) => `/web/certifications/${id}/download`,
      flowStatus: (id: number) => `/web/certifications/${id}/flow-status`,
    },
    clearance: {
      getAll: "/web/clearance",
      getById: (id: number) => `/web/clearance/${id}`,
      create: "/web/clearance",
      update: (id: number) => `/web/clearance/${id}`,
      delete: (id: number) => `/web/clearance/${id}`,
      approve: (id: number) => `/web/clearance/${id}/approve`,
      reject: (id: number) => `/web/clearance/${id}/reject`,
      generateDocument: (id: number) =>
        `/web/clearance/${id}/generate-document`,
      release: (id: number) => `/web/clearance/${id}/release`,
      receive: (id: number) => `/web/clearance/${id}/receive`,
      download: (id: number) => `/web/clearance/${id}/download`,
      flowStatus: (id: number) => `/web/clearance/${id}/flow-status`,
      configuration: "/web/clearance/configuration",
    },
    payments: {
      getAll: "/web/payments",
      getById: (id: number) => `/web/payments/${id}`,
      create: "/web/payments",
      receipt: (id: number) => `/web/payments/${id}/receipt`,
    },
    tax: {
      getAll: "/web/tax-payments",
      getById: (id: number) => `/web/tax-payments/${id}`,
      create: "/web/tax-payments",
      receipt: (id: number) => `/web/tax-payments/${id}/receipt`,
    },
    transactions: {
      getAll: "/web/transactions",
      getById: (id: number) => `/web/transactions/${id}`,
      summary: "/web/transactions/summary",
    },
    penalties: {
      getAll: "/web/penalties",
      getById: (id: number) => `/web/penalties/${id}`,
      create: "/web/penalties",
      update: (id: number) => `/web/penalties/${id}`,
      delete: (id: number) => `/web/penalties/${id}`,
    },
    frontdesk: {
      requests: "/web/frontdesk/requests",
      requestById: (id: number) => `/web/frontdesk/requests/${id}`,
      process: (id: number) => `/web/frontdesk/requests/${id}/process`,
      issue: (id: number) => `/web/frontdesk/requests/${id}/issue`,
      forward: (id: number) => `/web/frontdesk/requests/${id}/forward`,
      cancel: (id: number) => `/web/frontdesk/requests/${id}/cancel`,
      queue: "/web/frontdesk/queue",
      callNext: "/web/frontdesk/queue/call-next",
      appointments: "/web/frontdesk/appointments",
      claimSlips: "/web/frontdesk/claim-slips",
      residents: "/web/frontdesk/residents",
      tax: "/web/frontdesk/tax",
    },
    announcements: {
      getAll: "/web/announcements",
      getById: (id: number) => `/web/announcements/${id}`,
      create: "/web/announcements",
      update: (id: number) => `/web/announcements/${id}`,
      delete: (id: number) => `/web/announcements/${id}`,
      public: "/web/announcements/public",
    },
    barangay: {
      info: "/web/barangay-info",
      zones: "/web/barangay-zones",
    },
    geo: {
      houses: "/web/geo/houses",
      byHousehold: (householdId: number) =>
        `/web/geo/houses/household/${householdId}`,
      byZone: (zoneId: number) => `/web/geo/houses/zone/${zoneId}`,
    },
    records: {
      pending: "/web/records/pending",
      stats: "/web/records/stats",
      approve: (id: number) => `/web/records/${id}/approve`,
      reject: (id: number) => `/web/records/${id}/reject`,
    },
    activityLogs: {
      getAll: "/web/activity-logs",
      getByEncoder: (userId: number) => `/web/activity-logs/encoder/${userId}`,
      getByRecord: (recordId: number, recordType: string) =>
        `/web/activity-logs/record/${recordId}/${recordType}`,
    },
    financialReports: {
      getAll: "/web/financial-reports",
      getById: (id: number) => `/web/financial-reports/${id}`,
      create: "/web/financial-reports",
      update: (id: number) => `/web/financial-reports/${id}`,
      delete: (id: number) => `/web/financial-reports/${id}`,
      submit: (id: number) => `/web/financial-reports/${id}/submit`,
      approve: (id: number) => `/web/financial-reports/${id}/approve`,
      reject: (id: number) => `/web/financial-reports/${id}/reject`,
      pending: "/web/financial-reports/pending",
    },
    print: {
      receipt: (id: number) => `/web/print/receipt/${id}`,
      certificate: (id: number) => `/web/print/certificate/${id}`,
      taxReceipt: (id: number) => `/web/print/tax-receipt/${id}`,
      clearance: (id: number) => `/web/print/clearance/${id}`,
      claimSlip: (id: number) => `/web/print/claim-slip/${id}`,
    },
    roles: {
      getAll: "/web/roles",
      getById: (id: number) => `/web/roles/${id}`,
      create: "/web/roles",
      update: (id: number) => `/web/roles/${id}`,
      delete: (id: number) => `/web/roles/${id}`,
    },
    users: {
      getAll: "/web/users",
      getById: (id: number) => `/web/users/${id}`,
      update: (id: number) => `/web/users/${id}`,
      delete: (id: number) => `/web/users/${id}`,
      toggleStatus: (id: number) => `/web/users/${id}/toggle-status`,
    },
    dashboard: {
      stats: "/web/dashboard/stats",
    },
    system: {
      overview: "/web/system/overview",
      logs: "/web/system/logs",
    },
    accountActivation: {
      verify: "/account-activation/verify",
      request: "/account-activation/request",
    },
    health: {
      stats: "/web/health/stats",
      zoneStats: "/web/health/zone-statistics",
      searchResident: "/web/health/patients/search",
      createPatient: "/web/health/patients",
      pregnantRecords: "/web/health/records/pregnant",
      pregnancyDetails: (id: number) => `/web/health/records/pregnant/${id}`,
      pregnancyCheckup: (id: number) =>
        `/web/health/records/pregnant/${id}/checkup`,
      childrenRecords: "/web/health/records/children",
      childDetails: (id: number) => `/web/health/records/children/${id}`,
      childCheckup: (id: number) =>
        `/web/health/records/children/${id}/checkup`,
      lactatingRecords: "/web/health/records/lactating",
      lactatingDetails: (id: number) => `/web/health/records/lactating/${id}`,
      lactatingCheckup: (id: number) =>
        `/web/health/records/lactating/${id}/checkup`,
      seniorRecords: "/web/health/records/senior",
      seniorDetails: (id: number) => `/web/health/records/senior/${id}`,
      seniorCheckup: (id: number) => `/web/health/records/senior/${id}/checkup`,
      otherRecords: "/web/health/records/other",
      otherDetails: (id: number) => `/web/health/records/other/${id}`,
      otherCheckup: (id: number) => `/web/health/records/other/${id}/checkup`,
      notifyBHW: (id: number) => `/web/health/records/${id}/notify-bhw`,
      patients: "/web/health/patients",
      patientById: (id: number) => `/web/health/patients/${id}`,
      patientByResident: (residentId: number) =>
        `/web/health/patients/resident/${residentId}`,
      checkups: (patientRecordId: number) =>
        `/web/health/patients/${patientRecordId}/checkups`,
      createCheckup: (patientRecordId: number) =>
        `/web/health/patients/${patientRecordId}/checkups`,
      maternal: "/web/health/maternal",
      maternalById: (id: number) => `/web/health/maternal/${id}`,
      nutritionAssessments: "/web/health/nutrition/assessments",
      nutritionAssessmentById: (id: number) =>
        `/web/health/nutrition/assessments/${id}`,
      programs: "/web/health/programs",
      programById: (id: number) => `/web/health/programs/${id}`,
      programParticipants: (programId: number) =>
        `/web/health/programs/${programId}/participants`,
      programParticipant: (programId: number, participantId: number) =>
        `/web/health/programs/${programId}/participants/${participantId}`,
      checkupsByPatient: (patientRecordId: number) =>
        `/web/health/patients/${patientRecordId}/checkups`,
    },
    residentConfirmations: {
      getAll: "/web/resident-confirmations",
      create: "/web/resident-confirmations",
      getById: (id: number) => `/web/resident-confirmations/${id}`,
      confirm: (id: number) => `/web/resident-confirmations/${id}/confirm`,
      reject: (id: number) => `/web/resident-confirmations/${id}/reject`,
      myPending: "/web/resident-confirmations/my-pending",
      byResident: (residentId: number) =>
        `/web/resident-confirmations/resident/${residentId}`,
    },
    personnel: {
      getAll: "/web/personnel",
      byRole: (roleName: string) => `/web/personnel/role/${roleName}`,
      rolesWithCount: "/web/personnel/roles-with-count",
      stats: "/web/personnel/stats",
      assignRole: "/web/personnel/assign-role",
      removeRole: "/web/personnel/remove-role",
    },
  },
  bns: {
    dashboard: {
      stats: "/web/bns/dashboard/stats",
    },
    records: {
      getAll: "/web/bns/records",
      getById: (id: number) => `/web/bns/records/${id}`,
      export: "/web/bns/records/export",
    },
    consolidate: {
      byType: (type: string) => `/web/bns/consolidate/${type}`,
    },
    reports: {
      generate: "/web/bns/reports/generate",
      getById: (id: string) => `/web/bns/reports/${id}`,
      download: (id: string) => `/web/bns/reports/${id}/download`,
    },
    gis: {
      zoneStatistics: "/web/bns/zone-statistics",
      zoneStatisticsById: (zoneId: number) =>
        `/web/bns/zone-statistics/${zoneId}`,
    },
  },
} as const;